[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[functions."magister/magister"]
  timeout = 26

[functions."rain-check/rain-check"]
  schedule = "*/15 * * * *"

[functions."pomodoro-cron/pomodoro-cron"]
  schedule = "* * * * *"

[[headers]]
  for = "/simacan-arrival.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/simacan-arrival.html"
  to = "/simacan-arrival.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200